# Generated by Django 5.1.15 on 2026-01-15 16:50

from django.db import migrations


def create_initial_data(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Account = apps.get_model("phoneypay", "Account")

    admin_user = User.objects.create_superuser(
        username="admin", email="admin@example.com", password="PasswordAdmin"
    )
    Account.objects.create(owner=admin_user, phone="12345678", balance=1000)

    user1 = User.objects.create_user(username="user1", password="password1")
    Account.objects.create(owner=user1, phone="11111111", balance=50)

    user2 = User.objects.create_user(username="user2", password="password2")
    Account.objects.create(owner=user2, phone="22222222", balance=5000)

    user3 = User.objects.create_user(username="user3", password="password3")
    Account.objects.create(owner=user3, phone="33333333", balance=100000)


class Migration(migrations.Migration):
    dependencies = [
        ("phoneypay", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
